py h41.cmd('/usr/sbin/sshd -D &')
py h42.cmd('/usr/sbin/sshd -D &')
py h43.cmd('/usr/sbin/sshd -D &')
py h44.cmd('/usr/sbin/sshd -D &')
py h45.cmd('/usr/sbin/sshd -D &')
py h46.cmd('/usr/sbin/sshd -D &')
py h47.cmd('/usr/sbin/sshd -D &')
py h48.cmd('/usr/sbin/sshd -D &')
